create table public.admissions (
  id uuid not null,
  actual_discharge_date timestamp without time zone null,
  admission_date timestamp without time zone not null,
  admission_number character varying(30) null,
  admission_source character varying(30) not null,
  admission_type character varying(30) not null,
  approx_discharge_date timestamp without time zone null,
  attender_name character varying(100) null,
  attender_phone character varying(20) null,
  attender_relationship character varying(50) null,
  chief_complaint text null,
  created_at timestamp without time zone null,
  discharge_diagnosis text null,
  discharge_note text null,
  primary_diagnosis text null,
  status character varying(30) not null,
  updated_at timestamp without time zone null,
  admitting_doctor_id uuid null,
  created_by uuid null,
  department_id uuid null,
  hospital_id uuid not null,
  patient_id integer not null,
  room_id bigint null,
  source_appointment_id uuid null,
  ipd_id character varying(20) null,
  bed_id bigint null,
  previous_room_id bigint null,
  ot_booking_id uuid null,
  constraint admissions_pkey primary key (id),
  constraint ukd4apq4aodp80om8s3s1w1m7mq unique (ipd_id),
  constraint fkix6kc39n78hb7x6w05kvujpfm foreign KEY (admitting_doctor_id) references doctors (id),
  constraint admissions_previous_room_id_fkey foreign KEY (previous_room_id) references rooms (room_id),
  constraint fkmactdxy1of2dpq08ev7k7f3rs foreign KEY (department_id) references departments (id),
  constraint fkp7rb5vvnev5xv2i5bxl7l6o0e foreign KEY (source_appointment_id) references appointments (id),
  constraint fksw2l4n2yqlruoe741phfj9ae3 foreign KEY (hospital_id) references hospitals (id),
  constraint fk25rv1ihjai12ey1hexf3pk5u9 foreign KEY (created_by) references users (id),
  constraint fkbge98m8vnmk3fvlh1p9ljnmnm foreign KEY (bed_id) references beds (id),
  constraint fkjaaiv076g2j9pina6yskmv8hy foreign KEY (room_id) references rooms (room_id),
  constraint fkkyky6a6qqfqwfvd92qpopwepy foreign KEY (patient_id) references patients (patient_id),
  constraint admissions_status_check check (
    (
      (status)::text = any (
        (
          array[
            'ADMITTED'::character varying,
            'DISCHARGED'::character varying,
            'TRANSFERRED'::character varying,
            'ABSCONDED'::character varying
          ]
        )::text[]
      )
    )
  ),
  constraint admissions_admission_source_check check (
    (
      (admission_source)::text = any (
        (
          array[
            'OPD_REFERRAL'::character varying,
            'EMERGENCY_WALK_IN'::character varying,
            'DIRECT'::character varying,
            'TRANSFER_IN'::character varying
          ]
        )::text[]
      )
    )
  ),
  constraint admissions_admission_type_check check (
    (
      (admission_type)::text = any (
        array[
          ('OPD_REFERRAL'::character varying)::text,
          ('EMERGENCY'::character varying)::text,
          ('DIRECT'::character varying)::text
        ]
      )
    )
  )
) TABLESPACE pg_default;


create table public.ambulance_bookings (
  id bigint generated by default as identity not null,
  booking_date date not null,
  booking_time time without time zone not null,
  charge numeric(10, 2) null,
  created_at timestamp without time zone not null,
  destination_address text null,
  driver_name character varying(100) null,
  driver_phone character varying(20) null,
  notes text null,
  payment_status character varying(20) null,
  pickup_address text null,
  status character varying(20) not null,
  updated_at timestamp without time zone null,
  vehicle_number character varying(30) null,
  ambulance_type_id bigint null,
  hospital_id uuid not null,
  patient_id integer null,
  vehicle_id bigint null,
  merged_to_ipd boolean null,
  constraint ambulance_bookings_pkey primary key (id),
  constraint fki7q8t5bdr2jxmijlpnux36810 foreign KEY (hospital_id) references hospitals (id),
  constraint fkix175n6gpg7kpe7ruqcewo6kv foreign KEY (vehicle_id) references ambulance_vehicles (id),
  constraint fkok49rhbmxx2rfj4r1q6d7pfwg foreign KEY (ambulance_type_id) references ambulance_types (id),
  constraint fkqns5cc6kwjxei7a5ybkvpsggv foreign KEY (patient_id) references patients (patient_id),
  constraint ambulance_bookings_status_check check (
    (
      (status)::text = any (
        (
          array[
            'PENDING'::character varying,
            'DISPATCHED'::character varying,
            'EN_ROUTE'::character varying,
            'COMPLETED'::character varying,
            'CANCELLED'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;


create table public.ambulance_types (
  id bigint generated by default as identity not null,
  active boolean not null,
  default_charge numeric(10, 2) null,
  hospital_id uuid not null,
  name character varying(100) not null,
  constraint ambulance_types_pkey primary key (id)
) TABLESPACE pg_default;


create table public.ambulance_vehicles (
  id bigint generated by default as identity not null,
  created_at timestamp without time zone not null,
  default_charge numeric(10, 2) null,
  notes text null,
  status character varying(20) not null,
  updated_at timestamp without time zone null,
  vehicle_name character varying(100) null,
  vehicle_number character varying(30) not null,
  ambulance_type_id bigint null,
  hospital_id uuid not null,
  constraint ambulance_vehicles_pkey primary key (id),
  constraint fkalfemxncyynf9fnl6dy4utenp foreign KEY (ambulance_type_id) references ambulance_types (id),
  constraint fkjhfwqmbqfeljb8dbfptmugng1 foreign KEY (hospital_id) references hospitals (id),
  constraint ambulance_vehicles_status_check check (
    (
      (status)::text = any (
        (
          array[
            'AVAILABLE'::character varying,
            'IN_USE'::character varying,
            'MAINTENANCE'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;

create table public.appointments (
  id uuid not null,
  appt_date date not null,
  appt_end_time time without time zone null,
  appt_time time without time zone not null,
  branch_id uuid null,
  cancelled_reason text null,
  chief_complaint text null,
  created_at timestamp without time zone not null,
  status character varying(50) not null,
  token_number integer null,
  type character varying(50) not null,
  updated_at timestamp without time zone not null,
  created_by uuid not null,
  doctor_id uuid null,
  hospital_id uuid not null,
  patient_id integer not null,
  price_list_id uuid null,
  admission_id uuid null,
  checkup_booking_id uuid null,
  constraint appointments_pkey primary key (id),
  constraint fkt7nak2930bs3nwx862abgdh4o foreign KEY (price_list_id) references price_lists (id),
  constraint fkmujeo4tymoo98cmf7uj3vsv76 foreign KEY (doctor_id) references doctors (id),
  constraint fkpehidbpjidiw9nflgnpwymu6u foreign KEY (checkup_booking_id) references health_checkup_bookings (id),
  constraint fk6s7hx5emn6wtfjqet707k9j9a foreign KEY (admission_id) references admissions (id),
  constraint fk8exap5wmg8kmb1g1rx3by21yt foreign KEY (patient_id) references patients (patient_id),
  constraint appointments_type_check check (
    (
      (type)::text = any (
        (
          array[
            'OPD'::character varying,
            'FOLLOWUP'::character varying,
            'EMERGENCY'::character varying,
            'TELECONSULT'::character varying
          ]
        )::text[]
      )
    )
  ),
  constraint appointments_status_check check (
    (
      (status)::text = any (
        (
          array[
            'SCHEDULED'::character varying,
            'CONFIRMED'::character varying,
            'CHECKED_IN'::character varying,
            'IN_PROGRESS'::character varying,
            'COMPLETED'::character varying,
            'CANCELLED'::character varying,
            'NO_SHOW'::character varying,
            'BILLED'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;


create table public.appointments (
  id uuid not null,
  appt_date date not null,
  appt_end_time time without time zone null,
  appt_time time without time zone not null,
  branch_id uuid null,
  cancelled_reason text null,
  chief_complaint text null,
  created_at timestamp without time zone not null,
  status character varying(50) not null,
  token_number integer null,
  type character varying(50) not null,
  updated_at timestamp without time zone not null,
  created_by uuid not null,
  doctor_id uuid null,
  hospital_id uuid not null,
  patient_id integer not null,
  price_list_id uuid null,
  admission_id uuid null,
  checkup_booking_id uuid null,
  constraint appointments_pkey primary key (id),
  constraint fkt7nak2930bs3nwx862abgdh4o foreign KEY (price_list_id) references price_lists (id),
  constraint fkmujeo4tymoo98cmf7uj3vsv76 foreign KEY (doctor_id) references doctors (id),
  constraint fkpehidbpjidiw9nflgnpwymu6u foreign KEY (checkup_booking_id) references health_checkup_bookings (id),
  constraint fk6s7hx5emn6wtfjqet707k9j9a foreign KEY (admission_id) references admissions (id),
  constraint fk8exap5wmg8kmb1g1rx3by21yt foreign KEY (patient_id) references patients (patient_id),
  constraint appointments_type_check check (
    (
      (type)::text = any (
        (
          array[
            'OPD'::character varying,
            'FOLLOWUP'::character varying,
            'EMERGENCY'::character varying,
            'TELECONSULT'::character varying
          ]
        )::text[]
      )
    )
  ),
  constraint appointments_status_check check (
    (
      (status)::text = any (
        (
          array[
            'SCHEDULED'::character varying,
            'CONFIRMED'::character varying,
            'CHECKED_IN'::character varying,
            'IN_PROGRESS'::character varying,
            'COMPLETED'::character varying,
            'CANCELLED'::character varying,
            'NO_SHOW'::character varying,
            'BILLED'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;

create table public.asset_amc (
  id uuid not null,
  auto_alert_days integer null,
  contract_number character varying(255) null,
  contract_value double precision null,
  coverage_details character varying(255) null,
  created_at timestamp without time zone null,
  end_date date not null,
  start_date date not null,
  status character varying(255) null,
  visit_frequency character varying(255) null,
  asset_id uuid not null,
  vendor_id uuid not null,
  constraint asset_amc_pkey primary key (id),
  constraint fkp094jxgos0e46nis8vldswdk4 foreign KEY (asset_id) references assets (asset_id),
  constraint fkq8kefilngk4rt2sr5a7i0aods foreign KEY (vendor_id) references vendors (id)
) TABLESPACE pg_default;


create table public.asset_categories (
  id uuid not null,
  created_at timestamp without time zone null,
  depreciation_rate double precision null,
  hospital_id uuid not null,
  is_active boolean null,
  name character varying(255) not null,
  parent_id uuid null,
  useful_life_years integer null,
  constraint asset_categories_pkey primary key (id)
) TABLESPACE pg_default;


create table public.asset_maintenance (
  maintenance_id uuid not null,
  breakdown_details character varying(255) null,
  completed_at timestamp without time zone null,
  cost double precision null,
  created_at timestamp without time zone null,
  created_by uuid null,
  description character varying(255) null,
  maintenance_date date null,
  next_due_date date null,
  notes character varying(255) null,
  parts_replaced character varying(255) null,
  performed_by_user_id uuid null,
  repair_cost double precision null,
  scheduled_date date null,
  service_vendor character varying(255) null,
  started_at timestamp without time zone null,
  status character varying(255) null,
  type character varying(255) null,
  amc_id uuid null,
  asset_id uuid not null,
  performed_by_vendor_id uuid null,
  bank_account_id character varying(255) null,
  bank_account_name character varying(255) null,
  bill_number character varying(255) null,
  constraint asset_maintenance_pkey primary key (maintenance_id),
  constraint fk8lt280q9ldafevop8uibal9oh foreign KEY (asset_id) references assets (asset_id),
  constraint fke1e9i2hmlx72f6kga5t51tdjp foreign KEY (performed_by_vendor_id) references vendors (id),
  constraint fkihmpl6a9kli9p4mdc7qwc46na foreign KEY (amc_id) references asset_amc (id)
) TABLESPACE pg_default;


create table public.asset_maintenance (
  maintenance_id uuid not null,
  breakdown_details character varying(255) null,
  completed_at timestamp without time zone null,
  cost double precision null,
  created_at timestamp without time zone null,
  created_by uuid null,
  description character varying(255) null,
  maintenance_date date null,
  next_due_date date null,
  notes character varying(255) null,
  parts_replaced character varying(255) null,
  performed_by_user_id uuid null,
  repair_cost double precision null,
  scheduled_date date null,
  service_vendor character varying(255) null,
  started_at timestamp without time zone null,
  status character varying(255) null,
  type character varying(255) null,
  amc_id uuid null,
  asset_id uuid not null,
  performed_by_vendor_id uuid null,
  bank_account_id character varying(255) null,
  bank_account_name character varying(255) null,
  bill_number character varying(255) null,
  constraint asset_maintenance_pkey primary key (maintenance_id),
  constraint fk8lt280q9ldafevop8uibal9oh foreign KEY (asset_id) references assets (asset_id),
  constraint fke1e9i2hmlx72f6kga5t51tdjp foreign KEY (performed_by_vendor_id) references vendors (id),
  constraint fkihmpl6a9kli9p4mdc7qwc46na foreign KEY (amc_id) references asset_amc (id)
) TABLESPACE pg_default;


create table public.assets (
  asset_id uuid not null,
  amc_cost double precision null,
  amc_expiry date null,
  asset_code character varying(255) null,
  asset_name character varying(255) not null,
  assigned_to uuid null,
  assigned_to_type character varying(255) null,
  branch_id uuid null,
  created_at timestamp without time zone null,
  created_by uuid null,
  current_value double precision null,
  department_id uuid null,
  depreciation_rate double precision null,
  description character varying(255) null,
  disposal_reason character varying(255) null,
  disposal_value double precision null,
  disposed_on date null,
  hospital_id uuid null,
  location character varying(255) null,
  make character varying(255) null,
  model character varying(255) null,
  notes character varying(255) null,
  purchase_date date null,
  purchase_price double precision null,
  serial_number character varying(255) null,
  status character varying(255) null,
  useful_life_years integer null,
  warranty_expiry date null,
  category_id uuid null,
  product_id uuid null,
  vendor_id uuid null,
  assigned_at timestamp without time zone null,
  floor smallint null,
  room_id bigint null,
  constraint assets_pkey primary key (asset_id),
  constraint ukh3rqbypxh7aycu4jdf3sisunv unique (asset_code),
  constraint fkcwxkksxvxtrvv0sjtu5cgflep foreign KEY (category_id) references asset_categories (id),
  constraint fkmxkdbqw5qai7o3kcwsllg1u1q foreign KEY (vendor_id) references vendors (id),
  constraint fkt880ackvxx0f4y1i1t23m73xh foreign KEY (product_id) references products (id),
  constraint assets_assigned_to_type_check check (
    (
      (assigned_to_type)::text = any (
        (
          array[
            'USER'::character varying,
            'COMPANY'::character varying,
            'LOCATION'::character varying,
            'ROOM'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;


create table public.bank_accounts (
  id uuid not null,
  account_name character varying(255) not null,
  account_number character varying(255) null,
  account_type character varying(255) null,
  bank_name character varying(255) null,
  branch character varying(255) null,
  created_at timestamp without time zone null,
  hospital_id uuid not null,
  ifsc_code character varying(255) null,
  is_default boolean null,
  opening_balance numeric(15, 2) null,
  constraint bank_accounts_pkey primary key (id)
) TABLESPACE pg_default;


create table public.bank_transactions (
  id uuid not null,
  amount numeric(15, 2) not null,
  created_by uuid null,
  description character varying(255) null,
  hospital_id uuid not null,
  reference_no character varying(255) null,
  related_entity_id uuid null,
  related_entity_name character varying(255) null,
  related_entity_type character varying(255) null,
  transaction_date timestamp without time zone null,
  type character varying(255) not null,
  bank_account_id uuid not null,
  constraint bank_transactions_pkey primary key (id),
  constraint fklcu39w7fixvl9kv21tfx9tbhm foreign KEY (bank_account_id) references bank_accounts (id)
) TABLESPACE pg_default;


create table public.beds (
  id bigint generated by default as identity not null,
  bed_number character varying(20) not null,
  created_at timestamp without time zone not null,
  status character varying(20) not null,
  updated_at timestamp without time zone null,
  patient_id integer null,
  room_id bigint not null,
  constraint beds_pkey primary key (id),
  constraint uknwjyg3u7b9v863i0mp6gcwbin unique (room_id, bed_number),
  constraint fk2tg7eb23xlsy3mkhcqlp15aha foreign KEY (room_id) references rooms (room_id),
  constraint fk4h1eygo0cl2k08jyto7objc5t foreign KEY (patient_id) references patients (patient_id),
  constraint beds_status_check check (
    (
      (status)::text = any (
        (
          array[
            'AVAILABLE'::character varying,
            'OCCUPIED'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;


create table public.departments (
  id uuid not null,
  code character varying(20) null,
  created_at timestamp without time zone null,
  description text null,
  is_active boolean null,
  name character varying(100) not null,
  type character varying(30) not null,
  hospital_id uuid not null,
  constraint departments_pkey primary key (id),
  constraint uknt9fco0y6eokxt3kxs0fdcnf6 unique (hospital_id, name),
  constraint fkbvl4qy6xpecfnfmihch7j07im foreign KEY (hospital_id) references hospitals (id),
  constraint departments_type_check check (
    (
      (type)::text = any (
        (
          array[
            'CLINICAL'::character varying,
            'SUPPORT'::character varying,
            'ADMINISTRATIVE'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;


create table public.designations (
  id uuid not null,
  category character varying(30) not null,
  created_at timestamp without time zone null,
  is_active boolean null,
  name character varying(100) not null,
  department_id uuid null,
  hospital_id uuid not null,
  constraint designations_pkey primary key (id),
  constraint fk5kgb0o61xcwqr3scbtopsca3p foreign KEY (department_id) references departments (id),
  constraint fk8j5g3n2i7v4is8fhncaqp0inm foreign KEY (hospital_id) references hospitals (id),
  constraint designations_category_check check (
    (
      (category)::text = any (
        (
          array[
            'MEDICAL'::character varying,
            'NURSING'::character varying,
            'TECHNICAL'::character varying,
            'ADMINISTRATIVE'::character varying,
            'SUPPORT'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;


create table public.doctors (
  id uuid not null,
  available_days character varying(255) null,
  consultation_fee numeric(10, 2) null,
  created_at timestamp without time zone null,
  follow_up_fee numeric(10, 2) null,
  max_daily_slots integer null,
  medical_registration_number character varying(255) null,
  qualification character varying(255) null,
  registration_council character varying(255) null,
  slot_duration_min integer null,
  specialization character varying(255) null,
  updated_at timestamp without time zone null,
  hospital_id uuid not null,
  user_id uuid not null,
  personal_email character varying(255) null,
  personal_phone character varying(20) null,
  residential_address text null,
  work_address text null,
  work_email character varying(255) null,
  work_phone character varying(20) null,
  constraint doctors_pkey primary key (id),
  constraint ukt1f6cueqyjwx5ghew9ar1exe3 unique (user_id)
) TABLESPACE pg_default;


create table public.doctors (
  id uuid not null,
  available_days character varying(255) null,
  consultation_fee numeric(10, 2) null,
  created_at timestamp without time zone null,
  follow_up_fee numeric(10, 2) null,
  max_daily_slots integer null,
  medical_registration_number character varying(255) null,
  qualification character varying(255) null,
  registration_council character varying(255) null,
  slot_duration_min integer null,
  specialization character varying(255) null,
  updated_at timestamp without time zone null,
  hospital_id uuid not null,
  user_id uuid not null,
  personal_email character varying(255) null,
  personal_phone character varying(20) null,
  residential_address text null,
  work_address text null,
  work_email character varying(255) null,
  work_phone character varying(20) null,
  constraint doctors_pkey primary key (id),
  constraint ukt1f6cueqyjwx5ghew9ar1exe3 unique (user_id)
) TABLESPACE pg_default;


create table public.drug_alternatives (
  alternative_drug_id uuid not null,
  drug_id uuid not null,
  reason character varying(50) null,
  constraint drug_alternatives_pkey primary key (alternative_drug_id, drug_id)
) TABLESPACE pg_default;


create table public.drug_alternatives (
  alternative_drug_id uuid not null,
  drug_id uuid not null,
  reason character varying(50) null,
  constraint drug_alternatives_pkey primary key (alternative_drug_id, drug_id)
) TABLESPACE pg_default;


create table public.expense_categories (
  id uuid not null,
  created_at timestamp without time zone null,
  hospital_id uuid not null,
  is_active boolean null,
  name character varying(255) not null,
  constraint expense_categories_pkey primary key (id)
) TABLESPACE pg_default;


create table public.health_checkup_bookings (
  id uuid not null,
  amount_paid numeric(10, 2) null,
  booking_number character varying(20) null,
  created_at timestamp without time zone null,
  created_by character varying(100) null,
  doctor_notes text null,
  notes text null,
  payment_status character varying(20) null,
  recommendation text null,
  scheduled_date date not null,
  scheduled_time time without time zone null,
  status character varying(20) not null,
  updated_at timestamp without time zone null,
  doctor_id uuid null,
  package_id uuid not null,
  hospital_id uuid not null,
  patient_id integer not null,
  constraint health_checkup_bookings_pkey primary key (id),
  constraint uk8rybr6gld5sg2blcbekcsygp2 unique (booking_number),
  constraint fkk1vpdho6ct0axck8ntvjw0rqn foreign KEY (hospital_id) references hospitals (id),
  constraint fkadwg19j9j3s4xm7emniuvecpy foreign KEY (patient_id) references patients (patient_id),
  constraint fklmfr5keoi0ys83wbofyn77f5d foreign KEY (doctor_id) references doctors (id),
  constraint fkg4dgmo0twmip25ho1qgl53vot foreign KEY (package_id) references health_packages (id),
  constraint health_checkup_bookings_status_check check (
    (
      (status)::text = any (
        (
          array[
            'SCHEDULED'::character varying,
            'CHECKED_IN'::character varying,
            'IN_PROGRESS'::character varying,
            'COMPLETED'::character varying,
            'CANCELLED'::character varying,
            'NO_SHOW'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;


create table public.health_package_tests (
  id bigint generated by default as identity not null,
  display_order integer null,
  mandatory boolean not null,
  normal_range character varying(100) null,
  test_category character varying(50) null,
  test_name character varying(150) not null,
  package_id uuid not null,
  constraint health_package_tests_pkey primary key (id),
  constraint fkhiyp3l319m5y21folqby6yx57 foreign KEY (package_id) references health_packages (id)
) TABLESPACE pg_default;


create table public.health_packages (
  id uuid not null,
  active boolean not null,
  category character varying(30) not null,
  created_at timestamp without time zone null,
  description text null,
  name character varying(150) not null,
  price numeric(10, 2) not null,
  target_gender character varying(10) null,
  updated_at timestamp without time zone null,
  validity_days integer null,
  hospital_id uuid not null,
  constraint health_packages_pkey primary key (id),
  constraint fklherovyy96pngh18l7jac5qdj foreign KEY (hospital_id) references hospitals (id),
  constraint health_packages_category_check check (
    (
      (category)::text = any (
        (
          array[
            'GENERAL'::character varying,
            'CARDIAC'::character varying,
            'DIABETIC'::character varying,
            'CANCER_SCREENING'::character varying,
            'WOMENS_HEALTH'::character varying,
            'SENIOR'::character varying,
            'PAEDIATRIC'::character varying,
            'COMPREHENSIVE'::character varying,
            'CUSTOM'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;


create table public.health_packages (
  id uuid not null,
  active boolean not null,
  category character varying(30) not null,
  created_at timestamp without time zone null,
  description text null,
  name character varying(150) not null,
  price numeric(10, 2) not null,
  target_gender character varying(10) null,
  updated_at timestamp without time zone null,
  validity_days integer null,
  hospital_id uuid not null,
  constraint health_packages_pkey primary key (id),
  constraint fklherovyy96pngh18l7jac5qdj foreign KEY (hospital_id) references hospitals (id),
  constraint health_packages_category_check check (
    (
      (category)::text = any (
        (
          array[
            'GENERAL'::character varying,
            'CARDIAC'::character varying,
            'DIABETIC'::character varying,
            'CANCER_SCREENING'::character varying,
            'WOMENS_HEALTH'::character varying,
            'SENIOR'::character varying,
            'PAEDIATRIC'::character varying,
            'COMPREHENSIVE'::character varying,
            'CUSTOM'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;


create table public.hospital_floors (
  id bigint generated by default as identity not null,
  display_order integer null,
  name character varying(100) not null,
  building_id bigint not null,
  constraint hospital_floors_pkey primary key (id),
  constraint fkk14cdgt317sapyhsd5k7nbdee foreign KEY (building_id) references hospital_buildings (id)
) TABLESPACE pg_default;


create table public.hospital_modules (
  id uuid not null,
  activated_at timestamp without time zone null,
  created_at timestamp without time zone null,
  deactivated_at timestamp without time zone null,
  is_active boolean null,
  hospital_id uuid not null,
  module_id uuid not null,
  constraint hospital_modules_pkey primary key (id),
  constraint ukosthos009cdjt01uyogtn4y2p unique (hospital_id, module_id),
  constraint fkcn73q131q80psfovorxk09c13 foreign KEY (hospital_id) references hospitals (id),
  constraint fkdqie1xuoq5k6p23a685yg3gcx foreign KEY (module_id) references modules (id)
) TABLESPACE pg_default;


create table public.hospital_services (
  id uuid not null,
  created_at timestamp without time zone null,
  hospital_id uuid not null,
  is_active boolean null,
  name character varying(255) not null,
  price numeric(10, 2) not null,
  specialization_id uuid not null,
  updated_at timestamp without time zone null,
  gst_rate numeric(5, 2) null,
  constraint hospital_services_pkey primary key (id)
) TABLESPACE pg_default;


create table public.hospital_services (
  id uuid not null,
  created_at timestamp without time zone null,
  hospital_id uuid not null,
  is_active boolean null,
  name character varying(255) not null,
  price numeric(10, 2) not null,
  specialization_id uuid not null,
  updated_at timestamp without time zone null,
  gst_rate numeric(5, 2) null,
  constraint hospital_services_pkey primary key (id)
) TABLESPACE pg_default;


create table public.hospital_wards (
  id bigint generated by default as identity not null,
  daily_charge numeric(10, 2) null,
  display_order integer null,
  name character varying(100) not null,
  room_count integer null,
  floor_id bigint not null,
  constraint hospital_wards_pkey primary key (id),
  constraint fknvtcx5sqdaxixjo5ccdp7neti foreign KEY (floor_id) references hospital_floors (id)
) TABLESPACE pg_default;


create table public.hospital_wards (
  id bigint generated by default as identity not null,
  daily_charge numeric(10, 2) null,
  display_order integer null,
  name character varying(100) not null,
  room_count integer null,
  floor_id bigint not null,
  constraint hospital_wards_pkey primary key (id),
  constraint fknvtcx5sqdaxixjo5ccdp7neti foreign KEY (floor_id) references hospital_floors (id)
) TABLESPACE pg_default;


create table public.hospitals (
  id uuid not null,
  address character varying(255) null,
  city character varying(255) null,
  code character varying(255) null,
  created_at timestamp without time zone null,
  description character varying(255) null,
  email character varying(255) null,
  is_active boolean null,
  is_listed boolean null,
  logo_url character varying(255) null,
  name character varying(255) not null,
  phone character varying(255) null,
  state character varying(255) null,
  subdomain character varying(255) null,
  subscription_plan character varying(255) null,
  updated_at timestamp without time zone null,
  constraint hospitals_pkey primary key (id)
) TABLESPACE pg_default;


create table public.inventory_categories (
  id uuid not null,
  hospital_id uuid not null,
  is_active boolean null,
  name character varying(255) not null,
  parent_id uuid null,
  constraint inventory_categories_pkey primary key (id)
) TABLESPACE pg_default;


create table public.inventory_items (
  id uuid not null,
  category_id uuid null,
  code character varying(255) null,
  created_at timestamp without time zone null,
  description character varying(255) null,
  hospital_id uuid not null,
  is_active boolean null,
  last_price numeric(38, 2) null,
  name character varying(255) not null,
  preferred_vendor_id uuid null,
  reorder_level integer null,
  unit character varying(255) null,
  gst_percent integer null,
  batch_required boolean null,
  billable character varying(255) null,
  billing_group character varying(255) null,
  consumption_type character varying(255) null,
  expiry_required boolean null,
  item_type_id uuid null,
  pack_size integer null,
  purchase_price numeric(38, 2) null,
  selling_price numeric(38, 2) null,
  serial_required boolean null,
  drug_reorder_qty integer null,
  drug_schedule character varying(255) null,
  generic_name character varying(255) null,
  hsn_code character varying(255) null,
  constraint inventory_items_pkey primary key (id)
) TABLESPACE pg_default;


create table public.inventory_kits (
  id uuid not null,
  code character varying(255) null,
  created_at timestamp without time zone null,
  created_by uuid null,
  description character varying(255) null,
  hospital_id uuid not null,
  is_active boolean null,
  name character varying(255) not null,
  insurance_billing_price numeric(10, 2) null,
  patient_billing_price numeric(10, 2) null,
  constraint inventory_kits_pkey primary key (id)
) TABLESPACE pg_default;


create table public.inventory_stock (
  id uuid not null,
  hospital_id uuid not null,
  item_id uuid not null,
  last_updated timestamp without time zone null,
  quantity_avail numeric(38, 2) null,
  store_id uuid not null,
  constraint inventory_stock_pkey primary key (id)
) TABLESPACE pg_default;


create table public.invitations (
  invitation_id uuid not null,
  created_at timestamp without time zone not null,
  expires_at timestamp without time zone not null,
  invited_email character varying(255) not null,
  role character varying(50) not null,
  status character varying(20) not null,
  token character varying(255) not null,
  created_by uuid not null,
  hospital_id uuid not null,
  constraint invitations_pkey primary key (invitation_id),
  constraint ukt4i6esv44p6yi7cxq277vlo3i unique (token),
  constraint fkdk5jriaydqgx84bf7fx7k6wn9 foreign KEY (created_by) references users (id),
  constraint fkfs3b21xnv0miul48h69u656jy foreign KEY (hospital_id) references hospitals (id)
) TABLESPACE pg_default;


create table public.invoice_items (
  id uuid not null,
  description character varying(255) not null,
  quantity integer not null,
  service_id uuid null,
  total_price numeric(10, 2) not null,
  unit_price numeric(10, 2) not null,
  invoice_id uuid not null,
  item_type character varying(30) null,
  radiology_order_id bigint null,
  appointment_id uuid null,
  waiver_amount numeric(10, 2) null,
  waiver_reason character varying(255) null,
  ambulance_booking_id bigint null,
  constraint invoice_items_pkey primary key (id),
  constraint fk46ae0lhu1oqs7cv91fn6y9n7w foreign KEY (invoice_id) references invoices (id)
) TABLESPACE pg_default;


create table public.invoice_payments (
  id uuid not null,
  amount numeric(12, 2) not null,
  bank_account_id uuid null,
  collected_by character varying(100) null,
  notes character varying(255) null,
  paid_at timestamp without time zone null,
  payment_method character varying(30) null,
  invoice_id uuid not null,
  constraint invoice_payments_pkey primary key (id),
  constraint fkaa9if3io1iupfuqgsm0fbuch9 foreign KEY (invoice_id) references invoices (id)
) TABLESPACE pg_default;


create table public.invoices (
  id uuid not null,
  created_at timestamp without time zone null,
  discount numeric(10, 2) not null,
  invoice_number character varying(255) not null,
  notes text null,
  status character varying(20) not null,
  subtotal numeric(10, 2) not null,
  tax numeric(10, 2) not null,
  total numeric(10, 2) not null,
  updated_at timestamp without time zone null,
  appointment_id uuid null,
  hospital_id uuid not null,
  patient_id integer not null,
  specialization_id uuid null,
  payment_method character varying(50) null,
  admission_id uuid null,
  advance_adjusted numeric(10, 2) null,
  paid_amount numeric(10, 2) null,
  constraint invoices_pkey primary key (id),
  constraint ukl1x55mfsay7co0r3m9ynvipd5 unique (invoice_number),
  constraint fkmfoy3ff0vyx8yrbrvysffoc40 foreign KEY (specialization_id) references specializations (id),
  constraint fkjnop5n9opkiidvnj59w7af8bb foreign KEY (admission_id) references admissions (id),
  constraint fkrpyotno5h237hyoaokuggqqog foreign KEY (patient_id) references patients (patient_id),
  constraint fkngg5bc8atao2b9jehl9l8tdsw foreign KEY (appointment_id) references appointments (id),
  constraint fkmdskyllmnmki7r5978dr7mdv5 foreign KEY (hospital_id) references hospitals (id)
) TABLESPACE pg_default;

create index IF not exists idx_invoices_hospital_id on public.invoices using btree (hospital_id) TABLESPACE pg_default;

create index IF not exists idx_invoices_patient_id on public.invoices using btree (patient_id) TABLESPACE pg_default;

create index IF not exists idx_invoices_admission_id on public.invoices using btree (admission_id) TABLESPACE pg_default;

create index IF not exists idx_invoices_status on public.invoices using btree (status) TABLESPACE pg_default;

create index IF not exists idx_invoices_created_at on public.invoices using btree (created_at desc) TABLESPACE pg_default;


create table public.item_types (
  id uuid not null,
  default_batch_required boolean null,
  default_billable character varying(255) null,
  default_consumption_type character varying(255) null,
  default_expiry_required boolean null,
  hospital_id uuid not null,
  is_active boolean null,
  is_system boolean null,
  name character varying(255) not null,
  default_billing_group character varying(255) null,
  constraint item_types_pkey primary key (id)
) TABLESPACE pg_default;


create table public.kit_components (
  id uuid not null,
  quantity numeric(38, 2) not null,
  item_id uuid not null,
  kit_id uuid not null,
  constraint kit_components_pkey primary key (id),
  constraint fkfw9eib705fhf71xxgtowfy4se foreign KEY (item_id) references inventory_items (id),
  constraint fkqr072i3x63q2foymtjpm0j6ul foreign KEY (kit_id) references inventory_kits (id)
) TABLESPACE pg_default;


create table public.kit_consumptions (
  id uuid not null,
  consumed_at timestamp without time zone null,
  consumed_by uuid null,
  hospital_id uuid not null,
  kit_id uuid not null,
  notes character varying(255) null,
  quantity_consumed numeric(38, 2) not null,
  store_id uuid not null,
  constraint kit_consumptions_pkey primary key (id)
) TABLESPACE pg_default;


create table public.modules (
  id uuid not null,
  allowed_roles character varying(255) null,
  code character varying(255) not null,
  created_at timestamp without time zone null,
  description character varying(255) null,
  icon character varying(255) null,
  is_active boolean null,
  name character varying(255) not null,
  constraint modules_pkey primary key (id),
  constraint ukn5ng23nwasusfsyqk68hx5a05 unique (name),
  constraint ukr6b8cuvhddsfrycjnkvy3d3ig unique (code)
) TABLESPACE pg_default;


create table public.ot_bookings (
  id uuid not null,
  actual_end timestamp without time zone null,
  actual_start timestamp without time zone null,
  buffer_minutes integer not null,
  created_at timestamp without time zone not null,
  hospital_id uuid not null,
  notes character varying(1000) null,
  patient_id bigint not null,
  patient_mrn character varying(255) not null,
  patient_name character varying(255) not null,
  procedure_name character varying(255) not null,
  room_id bigint not null,
  room_name character varying(255) not null,
  scheduled_end timestamp without time zone not null,
  scheduled_start timestamp without time zone not null,
  status character varying(255) not null,
  surgeon_id uuid not null,
  surgeon_name character varying(255) not null,
  procedure_charge numeric(38, 2) null,
  sanitization_done boolean not null,
  sanitized_at timestamp without time zone null,
  admission_id uuid null,
  hms_patient_id integer null,
  hms_service_id uuid null,
  constraint ot_bookings_pkey primary key (id),
  constraint ot_bookings_status_check check (
    (
      (status)::text = any (
        (
          array[
            'REQUESTED'::character varying,
            'CONFIRMED'::character varying,
            'IN_PROGRESS'::character varying,
            'PENDING_SANITATION'::character varying,
            'COMPLETED'::character varying,
            'CANCELLED'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;


create table public.ot_consumption_items (
  id uuid not null,
  added_at timestamp without time zone not null,
  billable boolean not null,
  booking_id uuid not null,
  hospital_id uuid not null,
  inventory_item_id uuid null,
  item_name character varying(255) not null,
  item_type character varying(255) not null,
  quantity integer not null,
  unit_price double precision not null,
  constraint ot_consumption_items_pkey primary key (id),
  constraint ot_consumption_items_item_type_check check (
    (
      (item_type)::text = any (
        (
          array[
            'KIT'::character varying,
            'IMPLANT'::character varying,
            'CONSUMABLE'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;


create table public.ot_invoices (
  id uuid not null,
  admission_id uuid null,
  booking_id uuid null,
  created_at timestamp without time zone not null,
  hospital_id uuid not null,
  invoice_number character varying(255) not null,
  items_json text null,
  patient_id bigint not null,
  patient_name character varying(255) null,
  status character varying(20) null default 'UNPAID'::character varying,
  total_amount numeric(38, 2) null,
  constraint ot_invoices_pkey primary key (id),
  constraint uk4ptj2rgb944pwxg4dtfrdi3bi unique (invoice_number)
) TABLESPACE pg_default;


create table public.patient_advances (
  id uuid not null,
  amount numeric(10, 2) not null,
  applied boolean not null,
  applied_amount numeric(10, 2) null,
  applied_invoice_id uuid null,
  bank_account_id uuid null,
  collected_by character varying(100) null,
  created_at timestamp without time zone not null,
  notes character varying(255) null,
  payment_method character varying(50) null,
  receipt_number character varying(50) null,
  source character varying(20) not null,
  admission_id uuid null,
  hospital_id uuid not null,
  patient_id integer not null,
  constraint patient_advances_pkey primary key (id),
  constraint ukqwqjjo90w0hjc2l0y6rvf63w unique (receipt_number),
  constraint fk2vgxuuvf41ho01h3q7c06ry2f foreign KEY (patient_id) references patients (patient_id),
  constraint fkpait07xv9ubk0gf63g9suxgdb foreign KEY (hospital_id) references hospitals (id),
  constraint fkpki3qnt8olki00c1mord1nctg foreign KEY (admission_id) references admissions (id),
  constraint patient_advances_source_check check (
    (
      (source)::text = any (
        (
          array[
            'REGISTRATION'::character varying,
            'ADMISSION'::character varying,
            'TOPUP'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;


create table public.patient_records (
  history_id uuid not null,
  created_at timestamp without time zone not null,
  description text null,
  history_type character varying(50) not null,
  next_visit_date timestamp without time zone null,
  created_by uuid not null,
  hospital_id uuid not null,
  patient_id integer not null,
  admission_id uuid null,
  admission_number character varying(50) null,
  mrn character varying(30) null,
  constraint patient_records_pkey primary key (history_id),
  constraint uk225umlr65rb52hikljrp585hq unique (mrn),
  constraint fkp3i7exgh035i4miakj703j1si foreign KEY (patient_id) references patients (patient_id)
) TABLESPACE pg_default;


create table public.patient_services (
  id uuid not null,
  created_at timestamp without time zone null,
  hospital_id uuid not null,
  is_active boolean null,
  meal_time character varying(255) null,
  name character varying(255) not null,
  price_per_day numeric(10, 2) null,
  price_per_meal numeric(10, 2) null,
  type character varying(255) not null,
  updated_at timestamp without time zone null,
  charge_time character varying(5) null,
  one_time_charge boolean null,
  constraint patient_services_pkey primary key (id),
  constraint patient_services_meal_time_check check (
    (
      (meal_time)::text = any (
        (
          array[
            'BREAKFAST'::character varying,
            'LUNCH'::character varying,
            'DINNER'::character varying
          ]
        )::text[]
      )
    )
  ),
  constraint patient_services_type_check check (
    (
      (type)::text = any (
        (
          array[
            'FOOD'::character varying,
            'ROOM_SERVICE'::character varying,
            'CONVENIENCE'::character varying,
            'CUSTOM'::character varying,
            'REGISTRATION'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;


create table public.patients (
  patient_id integer generated by default as identity not null,
  address text null,
  blood_group character varying(5) null,
  created_at timestamp without time zone not null,
  dob date null,
  email character varying(100) null,
  first_name character varying(50) not null,
  gender character varying(10) not null,
  last_name character varying(50) not null,
  uhid character varying(20) not null,
  phone character varying(20) null,
  hospital_id uuid not null,
  state character varying(100) null,
  aadhaar_number character varying(12) null,
  allergies text null,
  chronic_conditions text null,
  emergency_contact_name character varying(100) null,
  emergency_contact_phone character varying(20) null,
  emergency_contact_relation character varying(50) null,
  insurance_policy_number character varying(50) null,
  insurance_scheme character varying(50) null,
  marital_status character varying(20) null,
  occupation character varying(100) null,
  referred_by character varying(100) null,
  payment_category character varying(10) null,
  mother_patient_id integer null,
  patient_type character varying(20) null default 'GENERAL'::character varying,
  constraint patients_pkey primary key (patient_id),
  constraint patients_hospital_id_uhid_key unique (hospital_id, uhid),
  constraint ukjjn14dd5d8mocm3etr8gacso2 unique (hospital_id, uhid),
  constraint uksb7msp304ilwygkujbpjnedw1 unique (hospital_id, uhid),
  constraint patients_payment_category_check check (
    (
      (payment_category)::text = any (
        (
          array[
            'CASH'::character varying,
            'CREDIT'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_patients_first_name on public.patients using btree (first_name) TABLESPACE pg_default;

create index IF not exists idx_patients_last_name on public.patients using btree (last_name) TABLESPACE pg_default;

create index IF not exists idx_patients_phone on public.patients using btree (phone) TABLESPACE pg_default;


create table public.payroll_records (
  id uuid not null,
  bank_account_id uuid null,
  bank_account_name character varying(255) null,
  base_salary numeric(15, 2) not null,
  bonus numeric(15, 2) not null,
  deductions numeric(15, 2) not null,
  department character varying(255) null,
  hospital_id uuid not null,
  month integer not null,
  net_pay numeric(15, 2) not null,
  payment_method character varying(255) null,
  processed_at timestamp without time zone not null,
  processed_by uuid null,
  role character varying(255) not null,
  staff_id uuid not null,
  staff_name character varying(255) not null,
  year integer not null,
  constraint payroll_records_pkey primary key (id)
) TABLESPACE pg_default;


create table public.pharmacy_bill_lines (
  id uuid not null,
  bill_id uuid not null,
  dispensing_id uuid not null,
  constraint pharmacy_bill_lines_pkey primary key (id)
) TABLESPACE pg_default;


create table public.pharmacy_bill_sequences (
  hospital_id uuid not null,
  last_number bigint not null,
  version bigint null,
  year integer not null,
  constraint pharmacy_bill_sequences_pkey primary key (hospital_id)
) TABLESPACE pg_default;


create table public.pharmacy_bill_sequences (
  hospital_id uuid not null,
  last_number bigint not null,
  version bigint null,
  year integer not null,
  constraint pharmacy_bill_sequences_pkey primary key (hospital_id)
) TABLESPACE pg_default;


create table public.pharmacy_bills (
  id uuid not null,
  bill_number character varying(50) not null,
  bill_type character varying(20) null,
  created_at timestamp without time zone null,
  created_by uuid not null,
  discount numeric(12, 2) null,
  finance_ledger_entry_id uuid null,
  gst_amount numeric(12, 2) null,
  hms_bill_line_id uuid null,
  hms_encounter_id uuid null,
  hospital_id uuid not null,
  patient_id uuid null,
  patient_phone character varying(20) null,
  payment_mode character varying(20) null,
  store_id uuid not null,
  total_amount numeric(12, 2) not null,
  constraint pharmacy_bills_pkey primary key (id),
  constraint ukk3gp2t5njuh7wk1gikr7dnvuk unique (bill_number)
) TABLESPACE pg_default;


create table public.pharmacy_drug_master (
  id uuid not null,
  brand_name character varying(255) not null,
  category character varying(50) null,
  chemical_class character varying(100) null,
  created_at timestamp without time zone null,
  form character varying(50) null,
  generic_name character varying(255) not null,
  hospital_id uuid not null,
  hsn_code character varying(10) null,
  image_url character varying(500) null,
  is_active boolean null,
  manufacturer_id uuid null,
  purpose character varying(500) null,
  reorder_qty integer null,
  salt_name character varying(200) null,
  schedule character varying(10) null,
  side_effects character varying(1000) null,
  strength character varying(100) null,
  strips_per_pack integer null,
  unit character varying(20) null,
  units_per_strip integer null,
  inventory_item_id uuid null,
  constraint pharmacy_drug_master_pkey primary key (id),
  constraint ukqwl4i9q1ag3tpbh8bv79sxu6y unique (hospital_id, brand_name, manufacturer_id)
) TABLESPACE pg_default;


create table public.pharmacy_narcotics_register (
  id uuid not null,
  balance_after numeric(10, 2) not null,
  batch_id uuid not null,
  created_at timestamp without time zone null,
  dispensing_id uuid not null,
  doctor_id uuid null,
  doctor_name character varying(255) not null,
  drug_id uuid not null,
  hospital_id uuid not null,
  patient_id uuid null,
  patient_name character varying(255) not null,
  qty numeric(10, 2) not null,
  store_id uuid not null,
  witnessed_by uuid null,
  constraint pharmacy_narcotics_register_pkey primary key (id)
) TABLESPACE pg_default;


create table public.pharmacy_stock_batches (
  id uuid not null,
  batch_number character varying(100) not null,
  created_at timestamp without time zone null,
  drug_id uuid not null,
  expiry_date date not null,
  hospital_id uuid not null,
  last_updated timestamp without time zone null,
  mrp numeric(10, 2) null,
  po_item_id uuid null,
  purchase_rate numeric(10, 2) null,
  received_qty numeric(10, 2) not null,
  selling_price numeric(10, 2) null,
  store_id uuid not null,
  constraint pharmacy_stock_batches_pkey primary key (id)
) TABLESPACE pg_default;


create table public.pharmacy_stock_batches (
  id uuid not null,
  batch_number character varying(100) not null,
  created_at timestamp without time zone null,
  drug_id uuid not null,
  expiry_date date not null,
  hospital_id uuid not null,
  last_updated timestamp without time zone null,
  mrp numeric(10, 2) null,
  po_item_id uuid null,
  purchase_rate numeric(10, 2) null,
  received_qty numeric(10, 2) not null,
  selling_price numeric(10, 2) null,
  store_id uuid not null,
  constraint pharmacy_stock_batches_pkey primary key (id)
) TABLESPACE pg_default;


create table public.po_bills (
  id uuid not null,
  bill_date date null,
  bill_number character varying(255) not null,
  created_at timestamp without time zone null,
  created_by uuid null,
  hospital_id uuid not null,
  invoice_number character varying(255) null,
  paid_amount numeric(12, 2) null,
  payment_status character varying(20) null,
  total_amount numeric(12, 2) null,
  purchase_order_id uuid not null,
  bank_account_id uuid null,
  bank_account_name character varying(255) null,
  constraint po_bills_pkey primary key (id),
  constraint uk5ug1ufby8okr3a7yj9i4tmaex unique (bill_number),
  constraint fknajf95d620b5vcaxht2qdt84v foreign KEY (purchase_order_id) references purchase_orders (id)
) TABLESPACE pg_default;


create table public.price_list_items (
  id uuid not null,
  is_active boolean not null,
  item_id uuid null,
  item_name character varying(200) not null,
  item_type character varying(50) not null,
  price numeric(10, 2) not null,
  price_list_id uuid not null,
  constraint price_list_items_pkey primary key (id),
  constraint fk90siqrejoko3qr15vcp3cdd1f foreign KEY (price_list_id) references price_lists (id),
  constraint price_list_items_item_type_check check (
    (
      (item_type)::text = any (
        (
          array[
            'CONSULTATION'::character varying,
            'ROOM_RENT'::character varying,
            'OT_CHARGE'::character varying,
            'LAB_TEST'::character varying,
            'PROCEDURE'::character varying,
            'NURSING'::character varying,
            'OTHER'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;


create table public.price_lists (
  id uuid not null,
  description text null,
  is_active boolean not null,
  is_default boolean not null,
  name character varying(100) not null,
  hospital_id uuid not null,
  constraint price_lists_pkey primary key (id),
  constraint fkrjbsk20lpqn4y8gnvsdodgr3u foreign KEY (hospital_id) references hospitals (id)
) TABLESPACE pg_default;


create table public.product_groups (
  id uuid not null,
  created_at timestamp without time zone null,
  hospital_id uuid not null,
  name character varying(255) not null,
  constraint product_groups_pkey primary key (id)
) TABLESPACE pg_default;


create table public.product_groups (
  id uuid not null,
  created_at timestamp without time zone null,
  hospital_id uuid not null,
  name character varying(255) not null,
  constraint product_groups_pkey primary key (id)
) TABLESPACE pg_default;


create table public.purchase_order_items (
  id uuid not null,
  quantity numeric(10, 2) not null,
  received_qty numeric(10, 2) null,
  total_price numeric(12, 2) null,
  unit_price numeric(10, 2) null,
  item_id uuid not null,
  po_id uuid not null,
  batch_number character varying(255) null,
  expiry_date date null,
  constraint purchase_order_items_pkey primary key (id),
  constraint fk5y0w29ahv8gqn5hq6ug5f9u9o foreign KEY (po_id) references purchase_orders (id),
  constraint fko7s0t0qc8uibo9mffoa6pwn5g foreign KEY (item_id) references inventory_items (id)
) TABLESPACE pg_default;


create table public.purchase_orders (
  id uuid not null,
  approved_by uuid null,
  created_at timestamp with time zone null,
  created_by uuid null,
  delivery_address text null,
  expected_date date null,
  hospital_id uuid not null,
  po_number character varying(255) not null,
  status character varying(20) null,
  total_amount numeric(12, 2) null,
  store_id uuid not null,
  vendor_id uuid not null,
  constraint purchase_orders_pkey primary key (id),
  constraint ukpbiykvcpyg0jslne4gviyeuc2 unique (po_number),
  constraint fkn3rssy7613r6x49ax30e2nbay foreign KEY (vendor_id) references vendors (id),
  constraint fkrkk3qf9gckmx5w6pwm1mmdefp foreign KEY (store_id) references stores (id)
) TABLESPACE pg_default;


create table public.purchase_orders (
  id uuid not null,
  approved_by uuid null,
  created_at timestamp with time zone null,
  created_by uuid null,
  delivery_address text null,
  expected_date date null,
  hospital_id uuid not null,
  po_number character varying(255) not null,
  status character varying(20) null,
  total_amount numeric(12, 2) null,
  store_id uuid not null,
  vendor_id uuid not null,
  constraint purchase_orders_pkey primary key (id),
  constraint ukpbiykvcpyg0jslne4gviyeuc2 unique (po_number),
  constraint fkn3rssy7613r6x49ax30e2nbay foreign KEY (vendor_id) references vendors (id),
  constraint fkrkk3qf9gckmx5w6pwm1mmdefp foreign KEY (store_id) references stores (id)
) TABLESPACE pg_default;


create table public.radiology_orders (
  id bigint generated by default as identity not null,
  bill_no character varying(50) null,
  created_at timestamp without time zone not null,
  created_by_name character varying(200) null,
  findings text null,
  observation text null,
  priority character varying(20) not null,
  referred_by_name character varying(200) null,
  report_id character varying(20) null,
  reported_at timestamp without time zone null,
  scanned_at timestamp without time zone null,
  scheduled_date date null,
  service_name character varying(200) not null,
  specialization_name character varying(200) null,
  status character varying(25) not null,
  technician_id uuid null,
  technician_name character varying(200) null,
  hospital_id uuid not null,
  patient_id integer not null,
  admission_id uuid null,
  constraint radiology_orders_pkey primary key (id),
  constraint fk8be25932ntyckckn2qwlrif1t foreign KEY (hospital_id) references hospitals (id),
  constraint fka8e1emvoysca8ejx42cxd5h49 foreign KEY (patient_id) references patients (patient_id),
  constraint fklqrf0yg9gnwds6rw20e0n37ei foreign KEY (admission_id) references admissions (id),
  constraint radiology_orders_priority_check check (
    (
      (priority)::text = any (
        (
          array[
            'ROUTINE'::character varying,
            'URGENT'::character varying,
            'STAT'::character varying
          ]
        )::text[]
      )
    )
  ),
  constraint radiology_orders_status_check check (
    (
      (status)::text = any (
        (
          array[
            'PENDING_SCAN'::character varying,
            'AWAITING_REPORT'::character varying,
            'REPORT_GENERATED'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;


create table public.room_logs (
  id bigint generated by default as identity not null,
  allocation_token character varying(30) null,
  attender_name character varying(100) null,
  created_at timestamp without time zone not null,
  event character varying(30) not null,
  patient_uhid character varying(50) null,
  patient_name character varying(200) null,
  performed_by character varying(200) null,
  room_number character varying(20) null,
  hospital_id uuid not null,
  room_id bigint not null,
  constraint room_logs_pkey primary key (id),
  constraint fkbe3wa3i8jnmrsl8m5xkcu76t5 foreign KEY (room_id) references rooms (room_id),
  constraint fkfoh1v8yw76y6ukyuhxefhsl6f foreign KEY (hospital_id) references hospitals (id),
  constraint room_logs_event_check check (
    (
      (event)::text = any (
        (
          array[
            'ROOM_CREATED'::character varying,
            'ALLOCATED'::character varying,
            'DEALLOCATED'::character varying,
            'ATTENDER_ASSIGNED'::character varying,
            'ATTENDER_UPDATED'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;


create table public.room_logs (
  id bigint generated by default as identity not null,
  allocation_token character varying(30) null,
  attender_name character varying(100) null,
  created_at timestamp without time zone not null,
  event character varying(30) not null,
  patient_uhid character varying(50) null,
  patient_name character varying(200) null,
  performed_by character varying(200) null,
  room_number character varying(20) null,
  hospital_id uuid not null,
  room_id bigint not null,
  constraint room_logs_pkey primary key (id),
  constraint fkbe3wa3i8jnmrsl8m5xkcu76t5 foreign KEY (room_id) references rooms (room_id),
  constraint fkfoh1v8yw76y6ukyuhxefhsl6f foreign KEY (hospital_id) references hospitals (id),
  constraint room_logs_event_check check (
    (
      (event)::text = any (
        (
          array[
            'ROOM_CREATED'::character varying,
            'ALLOCATED'::character varying,
            'DEALLOCATED'::character varying,
            'ATTENDER_ASSIGNED'::character varying,
            'ATTENDER_UPDATED'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;


create table public.specializations (
  id uuid not null,
  created_at timestamp without time zone null,
  description text null,
  hospital_id uuid not null,
  is_active boolean null,
  name character varying(255) not null,
  updated_at timestamp without time zone null,
  constraint specializations_pkey primary key (id)
) TABLESPACE pg_default;


create table public.specializations (
  id uuid not null,
  created_at timestamp without time zone null,
  description text null,
  hospital_id uuid not null,
  is_active boolean null,
  name character varying(255) not null,
  updated_at timestamp without time zone null,
  constraint specializations_pkey primary key (id)
) TABLESPACE pg_default;


create table public.staff_salaries (
  id uuid not null,
  basic_salary numeric(15, 2) not null,
  hospital_id uuid not null,
  staff_id uuid not null,
  updated_at timestamp without time zone null,
  constraint staff_salaries_pkey primary key (id),
  constraint uki10om1x7a7g90puh8ic4bl6pt unique (hospital_id, staff_id)
) TABLESPACE pg_default;


create table public.states (
  id uuid not null default gen_random_uuid (),
  state_name character varying(100) not null,
  state_code character varying(5) not null,
  gstin_code character varying(5) not null,
  region character varying(30) not null,
  is_union_territory boolean not null default false,
  capital character varying(100) null,
  pt_applicable boolean not null default false,
  lwf_applicable boolean not null default false,
  display_order integer not null,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint states_pkey primary key (id),
  constraint states_gstin_code_key unique (gstin_code),
  constraint states_state_code_key unique (state_code)
) TABLESPACE pg_default;


create table public.states (
  id uuid not null default gen_random_uuid (),
  state_name character varying(100) not null,
  state_code character varying(5) not null,
  gstin_code character varying(5) not null,
  region character varying(30) not null,
  is_union_territory boolean not null default false,
  capital character varying(100) null,
  pt_applicable boolean not null default false,
  lwf_applicable boolean not null default false,
  display_order integer not null,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint states_pkey primary key (id),
  constraint states_gstin_code_key unique (gstin_code),
  constraint states_state_code_key unique (state_code)
) TABLESPACE pg_default;


create table public.stock_batches (
  id uuid not null,
  batch_number character varying(255) null,
  created_at timestamp without time zone null,
  expiry_date date null,
  hospital_id uuid not null,
  item_id uuid not null,
  po_item_id uuid null,
  quantity_available numeric(10, 2) null,
  store_id uuid not null,
  constraint stock_batches_pkey primary key (id)
) TABLESPACE pg_default;


create table public.stock_transactions (
  id uuid not null,
  balance_after numeric(38, 2) not null,
  created_at timestamp without time zone null,
  created_by uuid null,
  hospital_id uuid not null,
  item_id uuid not null,
  quantity numeric(38, 2) not null,
  reference_id uuid null,
  reference_type character varying(255) null,
  remarks character varying(255) null,
  store_id uuid not null,
  transaction_type character varying(255) not null,
  constraint stock_transactions_pkey primary key (id)
) TABLESPACE pg_default;


create table public.stock_transactions (
  id uuid not null,
  balance_after numeric(38, 2) not null,
  created_at timestamp without time zone null,
  created_by uuid null,
  hospital_id uuid not null,
  item_id uuid not null,
  quantity numeric(38, 2) not null,
  reference_id uuid null,
  reference_type character varying(255) null,
  remarks character varying(255) null,
  store_id uuid not null,
  transaction_type character varying(255) not null,
  constraint stock_transactions_pkey primary key (id)
) TABLESPACE pg_default;


create table public.stores (
  id uuid not null,
  branch_id uuid null,
  department_id uuid null,
  hospital_id uuid not null,
  is_active boolean null,
  managed_by uuid null,
  name character varying(255) not null,
  type character varying(255) null,
  constraint stores_pkey primary key (id)
) TABLESPACE pg_default;


create table public.transfer_logs (
  transfer_id uuid not null,
  from_entity_id uuid null,
  from_entity_name character varying(255) null,
  remarks character varying(255) null,
  to_entity_id uuid null,
  to_entity_name character varying(255) null,
  transfer_date timestamp without time zone null,
  asset_id uuid null,
  constraint transfer_logs_pkey primary key (transfer_id),
  constraint fkj1i0hd84vdle7ni73oawgfup1 foreign KEY (asset_id) references assets (asset_id)
) TABLESPACE pg_default;


create table public.users (
  id uuid not null,
  branch_id uuid null,
  can_access_asset boolean null,
  can_access_hms boolean null,
  can_access_inventory boolean null,
  can_access_ot boolean null,
  can_access_pharmacy boolean null,
  created_at timestamp without time zone null,
  date_of_joining date null,
  department_id uuid null,
  designation character varying(255) null,
  email character varying(255) not null,
  employee_code character varying(255) null,
  first_name character varying(255) not null,
  gender character varying(255) null,
  google_id character varying(255) null,
  is_active boolean null,
  last_login_at timestamp without time zone null,
  last_name character varying(255) null,
  password_hash character varying(255) null,
  phone character varying(255) null,
  updated_at timestamp without time zone null,
  hospital_id uuid null,
  role_id uuid not null,
  state character varying(100) null,
  designation_id uuid null,
  aadhaar_number character varying(12) null,
  pan_number character varying(10) null,
  constraint users_pkey primary key (id),
  constraint ukkopv2hj98y95bwrl1i7dm86uh unique (employee_code, hospital_id),
  constraint ukob2dx53vn966ek0roock2539f unique (employee_code),
  constraint ukovh8xmu9ac27t18m56gri58i1 unique (google_id),
  constraint ukr6cx5bmlx0wilvqv72eevrlg3 unique (email, hospital_id),
  constraint fkp56c1712k691lhsyewcssf40f foreign KEY (role_id) references roles (id),
  constraint fkpp87ghj920xhrlf63rdeaufe1 foreign KEY (hospital_id) references hospitals (id),
  constraint fksbg59w8q63i0oo53rlgvlcnjq foreign KEY (department_id) references departments (id),
  constraint fk1x1ua9gs3wykwoajj3fv5s863 foreign KEY (designation_id) references designations (id)
) TABLESPACE pg_default;


create table public.ipd_vitals (
  id               uuid         not null default gen_random_uuid(),
  hospital_id      uuid         not null,
  admission_id     uuid         not null,
  patient_id       integer      not null,
  recorded_at      timestamp    not null,
  recorded_by      uuid         not null,
  bp_systolic      integer      null,
  bp_diastolic     integer      null,
  heart_rate       integer      null,
  respiratory_rate integer      null,
  temperature      numeric(4,1) null,
  spo2             integer      null,
  pain_score       integer      null,
  blood_glucose    integer      null,
  weight_kg        numeric(5,2) null,
  notes            text         null,
  created_at       timestamp    not null default now(),
  constraint ipd_vitals_pkey primary key (id),
  constraint fk_ipd_vitals_hospital  foreign key (hospital_id)  references hospitals (id),
  constraint fk_ipd_vitals_admission foreign key (admission_id) references admissions (id),
  constraint fk_ipd_vitals_patient   foreign key (patient_id)   references patients (patient_id),
  constraint fk_ipd_vitals_recorder  foreign key (recorded_by)  references users (id)
) TABLESPACE pg_default;

create index idx_ipd_vitals_admission_time
  on public.ipd_vitals (admission_id, recorded_at desc);
create table public.medication_administrations (
  id               uuid         not null default gen_random_uuid(),
  hospital_id      uuid         not null,
  admission_id     uuid         not null,
  order_id         uuid         not null,
  patient_id       integer      not null,
  administered_at  timestamp    not null,
  administered_by  uuid         not null,
  status           varchar(16)  not null,
  dose_given       varchar(100) null,
  reason           text         null,
  notes            text         null,
  created_at       timestamp    not null default now(),
  constraint medication_administrations_pkey primary key (id),
  constraint fk_med_admin_hospital  foreign key (hospital_id)  references hospitals (id),
  constraint fk_med_admin_admission foreign key (admission_id) references admissions (id),
  constraint fk_med_admin_order     foreign key (order_id)     references prescription_items (id),
  constraint fk_med_admin_patient   foreign key (patient_id)   references patients (patient_id),
  constraint fk_med_admin_nurse     foreign key (administered_by) references users (id),
  constraint chk_med_admin_status   check (status in ('GIVEN', 'HELD', 'REFUSED'))
) TABLESPACE pg_default;

create index idx_med_admin_admission
  on public.medication_administrations (admission_id, administered_at desc);

create index idx_med_admin_order
  on public.medication_administrations (order_id);
